fix(ci): comment out verify-phys on macOS
The system used for the job is expected to be offline for at least a
month, thus removing it to avoid blocking the pipeline.

Signed-off-by: Simon A. F. Lund <simon.lund@samsung.com>

diff --git a/.github/workflows/verify.yml b/.github/workflows/verify.yml
--- a/.github/workflows/verify.yml
+++ b/.github/workflows/verify.yml
@@ -764,98 +764,98 @@ jobs:
   #
   # Build and test xNVMe on physical machines
   #
-  verify-physical:
-    needs: [source-archive, source-format-check, build-python]
-    runs-on: ${{ matrix.guest.labels }}
-    if: github.event_name == 'push' || (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name,
-      'maas')) || (github.event_name == 'workflow_dispatch' && github.event.inputs.job == 'verify')
+  # verify-physical:
+  #   needs: [source-archive, source-format-check, build-python]
+  #   runs-on: ${{ matrix.guest.labels }}
+  #   if: github.event_name == 'push' || (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name,
+  #     'maas')) || (github.event_name == 'workflow_dispatch' && github.event.inputs.job == 'verify')
 
-    strategy:
-      fail-fast: false
-      matrix:
-        guest:
-        - {os: 'macos', ver: 'sonoma', hostname: 'verify-phys-macos', labels: [self-hosted, macos, arm64, verify]}
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       guest:
+  #       - {os: 'macos', ver: 'sonoma', hostname: 'verify-phys-macos', labels: [self-hosted, macos, arm64, verify]}
 
-    container:
-      image: debian:bookworm
-      options: --privileged
+  #   container:
+  #     image: debian:bookworm
+  #     options: --privileged
 
-    steps:
-    - uses: xnvme/actions/.github/actions/cleanup@main
+  #   steps:
+  #   - uses: xnvme/actions/.github/actions/cleanup@main
 
-    - name: Retrieve and unpack the xNVMe source archive
-      uses: xnvme/actions/.github/actions/setup-source@main
-      id: source
-      with:
-        name: xnvme-src-archive-with-subprojects
+  #   - name: Retrieve and unpack the xNVMe source archive
+  #     uses: xnvme/actions/.github/actions/setup-source@main
+  #     id: source
+  #     with:
+  #       name: xnvme-src-archive-with-subprojects
 
-    - name: Retrieve the xNVMe Python sdist package
-      uses: actions/download-artifact@v4.1.7
-      with:
-        name: xnvme-py-sdist
-        path: ${{ steps.source.outputs.directory }}
+  #   - name: Retrieve the xNVMe Python sdist package
+  #     uses: actions/download-artifact@v4.1.7
+  #     with:
+  #       name: xnvme-py-sdist
+  #       path: ${{ steps.source.outputs.directory }}
 
-    - name: Prep, environment GITHUB_PATH
-      run: |
-        echo "$HOME/.local/bin" >> $GITHUB_PATH
-        cp -r ${{ steps.source.outputs.directory }} /tmp/artifacts
-        find /tmp/artifacts
+  #   - name: Prep, environment GITHUB_PATH
+  #     run: |
+  #       echo "$HOME/.local/bin" >> $GITHUB_PATH
+  #       cp -r ${{ steps.source.outputs.directory }} /tmp/artifacts
+  #       find /tmp/artifacts
 
-    - name: Packages
-      run: |
-        apt-get -qy update
-        apt-get -qy upgrade
-        apt-get -qy install python3 python3-dev python3-venv pipx git make gcc fontconfig sshpass
-        pipx ensurepath
+  #   - name: Packages
+  #     run: |
+  #       apt-get -qy update
+  #       apt-get -qy upgrade
+  #       apt-get -qy install python3 python3-dev python3-venv pipx git make gcc fontconfig sshpass
+  #       pipx ensurepath
 
-    - name: CIJOE, setup pipx environment
-      run: |
-        make cijoe
-        cijoe --version
+  #   - name: CIJOE, setup pipx environment
+  #     run: |
+  #       make cijoe
+  #       cijoe --version
 
-    # cd'ing into 'cijoe' to auto-collect the non-packaged github-specific configs and
-    # workflows.
-    - name: CIJOE, run macvfn-provision.yaml
-      if: matrix.guest.os == 'macos'
-      run: |
-        cd cijoe && cijoe "workflows/macvfn-provision.yaml" \
-        --monitor \
-        --config "configs/${{ matrix.guest.hostname }}.toml" \
-        --output "${{ github.job }}-${{ matrix.guest.hostname }}-provision-macvfn"
+  #   # cd'ing into 'cijoe' to auto-collect the non-packaged github-specific configs and
+  #   # workflows.
+  #   - name: CIJOE, run macvfn-provision.yaml
+  #     if: matrix.guest.os == 'macos'
+  #     run: |
+  #       cd cijoe && cijoe "workflows/macvfn-provision.yaml" \
+  #       --monitor \
+  #       --config "configs/${{ matrix.guest.hostname }}.toml" \
+  #       --output "${{ github.job }}-${{ matrix.guest.hostname }}-provision-macvfn"
 
-    - name: CIJOE, run provisioning
-      run: |
-        cd cijoe && cijoe "workflows/provision-using-tgz.yaml" \
-        --monitor \
-        --config "configs/${{ matrix.guest.hostname }}.toml" \
-        --output "${{ github.job }}-${{ matrix.guest.hostname }}-provision-xnvme" \
-        xnvme_source_sync xnvme_build_prep xnvme_build xnvme_install \
-        ldconfig xnvme_bindings_py_install_tgz fio_prep
+  #   - name: CIJOE, run provisioning
+  #     run: |
+  #       cd cijoe && cijoe "workflows/provision-using-tgz.yaml" \
+  #       --monitor \
+  #       --config "configs/${{ matrix.guest.hostname }}.toml" \
+  #       --output "${{ github.job }}-${{ matrix.guest.hostname }}-provision-xnvme" \
+  #       xnvme_source_sync xnvme_build_prep xnvme_build xnvme_install \
+  #       ldconfig xnvme_bindings_py_install_tgz fio_prep
 
-    - name: CIJOE, run tests
-      run: |
-        cd cijoe && cijoe "workflows/test-${{ matrix.guest.os }}-${{ matrix.guest.ver }}.yaml" \
-        --monitor \
-        --config "configs/${{ matrix.guest.hostname }}.toml" \
-        --output "${{ github.job }}-${{ matrix.guest.hostname }}-test-results"
+  #   - name: CIJOE, run tests
+  #     run: |
+  #       cd cijoe && cijoe "workflows/test-${{ matrix.guest.os }}-${{ matrix.guest.ver }}.yaml" \
+  #       --monitor \
+  #       --config "configs/${{ matrix.guest.hostname }}.toml" \
+  #       --output "${{ github.job }}-${{ matrix.guest.hostname }}-test-results"
 
-    - name: CIJOE, result-log-dump on error
-      if: failure()
-      run: find cijoe -name "*.output" | xargs cat
+  #   - name: CIJOE, result-log-dump on error
+  #     if: failure()
+  #     run: find cijoe -name "*.output" | xargs cat
 
-    - name: CIJOE, archive verify-${{ matrix.guest.hostname }}-reports
-      if: always()
-      run: |
-        tar czf ${{ github.job }}-${{ matrix.guest.hostname }}-reports.tar.gz \
-          cijoe/${{ github.job }}-${{ matrix.guest.hostname }}-* 
+  #   - name: CIJOE, archive verify-${{ matrix.guest.hostname }}-reports
+  #     if: always()
+  #     run: |
+  #       tar czf ${{ github.job }}-${{ matrix.guest.hostname }}-reports.tar.gz \
+  #         cijoe/${{ github.job }}-${{ matrix.guest.hostname }}-* 
 
-    - name: CIJOE, upload verify-${{ matrix.guest.hostname }}-reports
-      uses: actions/upload-artifact@v4.3.0
-      if: always()
-      with:
-        name: ${{ github.job }}-${{ matrix.guest.hostname }}-reports
-        path: ${{ github.job }}-${{ matrix.guest.hostname }}-reports.tar.gz
-        if-no-files-found: error
+  #   - name: CIJOE, upload verify-${{ matrix.guest.hostname }}-reports
+  #     uses: actions/upload-artifact@v4.3.0
+  #     if: always()
+  #     with:
+  #       name: ${{ github.job }}-${{ matrix.guest.hostname }}-reports
+  #       path: ${{ github.job }}-${{ matrix.guest.hostname }}-reports.tar.gz
+  #       if-no-files-found: error
 
   #
   # Build and test xNVMe on physical hardware on MaaS
